version: "3.8"
services:

  nginx:
    image: nginx:1-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
    - ./../:/var/www/html/
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    restart: always
    build:
      context: ./../
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./../:/var/www/html/
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres